services:
    _defaults:
        public: true

    OroTaskBundleRestApiController:
        namespace: Oro\Bundle\TaskBundle\Controller\Api\Rest\
        resource: '../../Controller/Api/Rest/*Controller.php'
        calls:
            - [setContainer, ['@service_container']]
