api:
    entities:
        Oro\Bundle\TaskBundle\Entity\Task:
            documentation_resource: '@OroTaskBundle/Resources/doc/api/task.md'
            filters:
                fields:
                    ownerUsername:
                        data_type: string
                        property_path: owner.username
            subresources:
                createdBy:
                    actions:
                        get_subresource: true
                        get_relationship: true
                        update_relationship: false
            actions:
                update_list: true

        Oro\Bundle\TaskBundle\Entity\TaskPriority:
            documentation_resource: '@OroTaskBundle/Resources/doc/api/task.md'
            filters:
                fields:
                    order: ~
            sorters:
                fields:
                    order: ~

        Extend\Entity\EV_Task_Status:
            documentation_resource: '@OroTaskBundle/Resources/doc/api/task.md'
