datagrids:
    tasks-grid:
        extended_entity_name: 'Oro\Bundle\TaskBundle\Entity\Task'
        acl_resource: oro_task_view
        source:
            type: orm
            query:
                select:
                    - task.id
                    - task.subject
                    - task.description
                    - task.dueDate
                    - tp.name as taskPriority
                    - tp.label as priorityLabel
                    - CONCAT_WS(' ', own.firstName, own.lastName) as ownerName
                    - own.id as owner
                    - task.createdAt
                    - task.updatedAt
                    - ts.id as status
                    - ts.name as statusLabel
                from:
                    - { table: 'Oro\Bundle\TaskBundle\Entity\Task', alias: task }
                join:
                    inner:
                        - { join: task.taskPriority, alias: tp }
                        - { join: task.owner, alias: own }
                        - { join: task.status, alias: ts }
        inline_editing:
            enable: true
        columns:
            subject:
                label:         oro.task.subject.label
            dueDate:
                label:         oro.task.due_date.label
                frontend_type: datetime
            status:
                label:         oro.task.status.label
                frontend_type: select
                choices: "@oro_entity_extend.enum_value_provider->getEnumChoicesByCode('task_status')"
                translatable_options: false
                inline_editing:
                    enable: true
            taskPriority:
                label:         oro.task.task_priority.label
                frontend_type: select
            ownerName:
                label:         oro.task.owner.label
                inline_editing:
                    enable: true
                    editor:
                        view: oroform/js/app/views/editor/related-id-relation-editor-view
                        view_options:
                            value_field_name: owner
                    autocomplete_api_accessor:
                        class: orouser/js/tools/acl-users-search-api-accessor
                        permission_check_entity_name: Oro_Bundle_TaskBundle_Entity_Task
            createdAt:
                label:         oro.ui.created_at
                frontend_type: datetime
            updatedAt:
                label:         oro.ui.updated_at
                frontend_type: datetime
            tags: []
            contexts: []

        sorters:
            columns:
                subject:
                    data_name: task.subject
                dueDate:
                    data_name: task.dueDate
                status:
                    data_name: ts.priority
                taskPriority:
                    data_name: tp.order
                ownerName:
                    data_name: ownerName
                createdAt:
                    data_name: task.createdAt
                updatedAt:
                    data_name: task.updatedAt
            default:
                dueDate: ASC
        filters:
            columns:
                subject:
                    type:      string
                    data_name: task.subject
                dueDate:
                    type:      datetime
                    data_name: task.dueDate
                status:
                    type:      enum
                    data_name: task.status
                    enum_code: task_status
                priorityLabel:
                    label: oro.task.task_priority.label
                    type:      string
                    data_name: priorityLabel
                owner:
                    type: choice-tree
                    label: oro.task.owner.label
                    data_name: task.owner
                    autocomplete_alias: assigned_to_organization_users
                    renderedPropertyName: 'fullName'
                    className: 'Oro\Bundle\UserBundle\Entity\User'
                businessUnitId:
                    label: oro.business_unit.label
                    type: choice-business-unit
                    data_name: task.owner
                    className: 'Oro\Bundle\OrganizationBundle\Entity\BusinessUnit'
                createdAt:
                    type:      datetime
                    data_name: task.createdAt
                updatedAt:
                    type:      datetime
                    data_name: task.updatedAt
        properties:
            id: ~
            owner: ~
            view_link:
                type:       url
                route:      oro_task_view
                params:     [ id ]
            update_link:
                type:       url
                route:      oro_task_update
                params:     [ id ]
        actions:
            view:
                type:          navigate
                acl_resource:  oro_task_view
                label:         oro.grid.action.view
                icon:          eye
                link:          view_link
                rowAction:     true
            update:
                type:          navigate
                acl_resource:  oro_task_update
                label:         oro.grid.action.update
                icon:          edit
                link:          update_link
        options:
            entity_pagination: true
            contexts:
                enabled: true

    widget-base-tasks-grid:
        acl_resource: oro_task_view
        source:
            type: orm
            query:
                select:
                    - task.id
                    - task.subject
                    - task.dueDate
                    - taskPriority.label as priorityLabel
                    - CONCAT_WS(' ', owner.firstName, owner.lastName) as ownerName
                    - owner.id as ownerId
                    - ts.id as taskStatus
                    - ts.name as statusLabel
                from:
                    - { table: 'Oro\Bundle\TaskBundle\Entity\Task', alias: task }
                join:
                    left:
                        - { join: task.taskPriority, alias: taskPriority }
                        - { join: task.owner, alias: owner }
                        - { join: task.status, alias: ts }
        columns:
            subject:
                label:         oro.task.subject.label
                type:          twig
                template:      '@OroTask/Task/Datagrid/Property/subject.html.twig'
                frontend_type: html
            dueDate:
                label:         oro.task.due_date.label
                frontend_type: datetime
            statusLabel:
                label:         oro.task.status.label
            priorityLabel:
                label:         oro.task.task_priority.label
            ownerName:
                type:          twig
                label:         oro.task.owner.label
                frontend_type: html
                template:      '@OroTask/Task/Datagrid/Property/owner.html.twig'
        sorters:
            columns:
                subject:
                    data_name: task.subject
                dueDate:
                    data_name: task.dueDate
                statusLabel:
                    data_name: ts.priority
                priorityLabel:
                    data_name: taskPriority.order
                ownerName:
                    data_name: ownerName
            default:
                dueDate: ASC
        filters:
            columns:
                subject:
                    type:      string
                    data_name: task.subject
                dueDate:
                    type:      datetime
                    data_name: task.dueDate
                statusLabel:
                    type:      enum
                    data_name: taskStatus
                    enum_code: task_status
                priorityLabel:
                    type:      string
                    data_name: priorityLabel
                ownerName:
                    type:      string
                    data_name: ownerName
        properties:
            id: ~

    activity-tasks-grid:
        extends: widget-base-tasks-grid

    user-tasks-grid:
        extends: tasks-grid
        options:
            entity_pagination: false

    task-for-context-grid:
        extended_entity_name: 'Oro\Bundle\TaskBundle\Entity\Task'
        acl_resource: oro_task_view
        options:
            entityHint: oro.task.entity_plural_label
            entity_pagination: true
            toolbarOptions:
                pageSize:
                    default_per_page: 10
            routerEnabled: false

        source:
            type: orm
            query:
                select:
                    - task.id
                    - task.subject
                    - task.description
                    - task.dueDate
                    - tp.name as taskPriority
                    - tp.label as priorityLabel
                    - CONCAT_WS(' ', own.firstName, own.lastName) as ownerName
                    - own.id as owner
                    - ts.id as taskStatus
                    - ts.name as statusLabel
                from:
                    - { table: 'Oro\Bundle\TaskBundle\Entity\Task', alias: task }
                join:
                    left:
                        - { join: task.taskPriority, alias: tp }
                        - { join: task.owner, alias: own }
                        - { join: task.status, alias: ts }
            hints:
                - HINT_TRANSLATABLE
        columns:
            id:
                label:         oro.task.id.label
            subject:
                label:         oro.task.subject.label
            dueDate:
                label:         oro.task.due_date.label
                frontend_type: datetime
            statusLabel:
                label:         oro.task.status.label
            taskPriority:
                label:         oro.task.task_priority.label
            ownerName:
                label:         oro.task.owner.label
        sorters:
            columns:
                subject:
                    data_name: task.subject
                dueDate:
                    data_name: task.dueDate
                statusLabel:
                    data_name: ts.priority
                taskPriority:
                    data_name: tp.order
                ownerName:
                    data_name: ownerName
            default:
                dueDate: ASC
        filters:
            columns:
                subject:
                    type:      string
                    data_name: task.subject
                dueDate:
                    type:      datetime
                    data_name: task.dueDate
                statusLabel:
                    type:      enum
                    data_name: taskStatus
                    enum_code: task_status
                priorityLabel:
                    label:     oro.task.task_priority.label
                    type:      string
                    data_name: priorityLabel
                owner:
                    type: choice-tree
                    label: oro.task.owner.label
                    data_name: task.owner
                    options:
                        lazy: "@oro_user.provider.filter.user_choice_tree->shouldBeLazy"
                        data: "@?oro_user.provider.filter.user_choice_tree->getList"
